### ISSUE TITLE
Touch devices will cause a Print command trying to click Delete

### ISSUE THREAD

**Issue by dcs619** [KingdomFirst/rock-attended-checkin#29]
Depending on the touch device, someone trying to remove a check-in record can fat-finger the touch and it will register as a row command.  

Since `OnRowCommand` is set to Print the end result is an extra (incorrect) label instead of deleting the check-in record.

**Comment by kyeschung** [comment]
Yes, this is a major issue and MOST of the time you press the delete X, it prints out more labels.

**Comment by dcs619** [comment]
I believe I've narrowed this issue down, it only happens for USB configured printers.

**Comment by nateh777** [comment]
Attempted to reproduce and I believe due to the age of this issue I am no longer able to produce the same result. If we can get more specific data, such as what devices are prone to this issue, I can test again. I tested on my computer and a touch screen windows device (Lenovo Yoga) and I was unable to produce any "fat finger" result. Closing this issue.
