### ISSUE TITLE
Search Bar loses or resets focus

### ISSUE THREAD

**Issue by paultedder** [KingdomFirst/rock-attended-checkin#53]
On Touchscreen chromebooks we have noticed that after 2-3 seconds of inactivity in the search bar that the search bar loses focus.  This does not happen on non-touchscreen chromebooks or Windows machines using Chrome.
We have also found a related issue on Windows machines using Chrome where if you start typing in the search box; stop for a couple seconds, that it returns the cursor to the beginning of the field (which can create misspellings or confusion)

**Comment by eddieholeman** [comment]
Is there a scheduled release for this fix?

**Comment by dcs619** [comment]
It was supposed to be this week, however the more I thought about this I don't know that it's fixable.  If you have a touchscreen then focusing the search bar at any point will open the onscreen keyboard, thereby hiding the touchpad number selector (if that's what your checkin area is configured for).  

The loss of focus is due to the client page looking for checkin updates according to the Checkin Area > Refresh seconds.  

If it's not a touch device, the code I've updated does return focus to the end of the line instead of the beginning.

**Comment by eddieholeman** [comment]
Just to be clear David, we moved off of touchscreen Chromebooks because this was too big of an issue. The problem continues on non-touchscreen devices, so your fix of return focus to the end of the line instead of the beginning would be perfect.  We would love to get this as soon as possible.
