### ISSUE TITLE
Barcode Scanning not finding any families

### ISSUE THREAD

**Issue by BEGamache** [KingdomFirst/rock-attended-checkin#72]
I have compared Core's Welcome block code with Attended's Search block code and can't figure out what is causing Attended Check-in to not properly by the barcode ID.

Attended Check-in properly scans the barcode but doesn't pull up any families or people. I have clicked the back button to make sure the right barcode value was entered into the search bar and it was. I have also made sure the value that was searched matches the alternate ID on the person's profile record. Scanning with Core's check-in works great so I don't think it is a workflow issue but a block code issue in Attended Check-in, unless something isn't getting passed from the workflow back to the block or viewstate.

**Comment by calvmann** [comment]
I have noticed the same thing with our instance

**Comment by calvmann** [comment]
This was closed but I am still experiencing the same issue that was originally reported.

**Comment by nateh777** [comment]
@calvmann I am sorry you are still experiencing this issue. Unfortunately, we do not have a barcode scanner to properly reproduce this issue. From what I could reproduce, using a simulated barcode, it was working correctly with v11.3 and "Enable Search Auto Focus" set to "No". It is possible that this issue is present again in v12. If you could produce a sample video of the issue you are experiencing it may help us to further look into this issue. If you could file it as a new issue of what you are seeing with the video sample that would be great.
