### ISSUE TITLE
B: Grade in Block setting not displaying properly

### ISSUE THREAD

**Issue by calvmann** [KingdomFirst/rock-attended-checkin#95]
**Expected Behavior**
When adding School Grades under Defined Types, the newly added grades don't display properly in the checkin summary screen.

**Current Behavior**
When you add a grade of PreK with abbreviation PreK, the grade displays as K in the summary screen (K also displays for the grade 'Kindergarten' which is why this could be confusing) 

**Steps to Reproduce**
In Defined Types > School Grades, add a PreK grade with abbreviation PreK
In the block setting for Attended Checkin Confirmation Page, enable the ability to display age/grade.
Check in an individual who has PreK set as their grade.

**Context**
Rock Version: 12.7
Attended Check-in Version: 1.8.5

<img width="1063" alt="Screen Shot 2022-02-28 at 9 02 02 AM" src="https://user-images.githubusercontent.com/38733976/156005778-707bef13-21a3-4dca-b244-0af2f027acf0.png">

![IMG_9193](https://user-images.githubusercontent.com/38733976/156005618-ef673454-cd37-4a5a-a696-204931bab5ce.jpg)

![IMG_9192 copy](https://user-images.githubusercontent.com/38733976/156005643-23b70d78-ee7b-4eb5-8e2b-3066dc30cccf.jpg)

**Comment by nateh777** [comment]
Confirmed, anything "above" 12 in the value is labeled K due to the grade offset methods used by Rock, not exactly sure of the reasoning for the K, but also not sure of the repercussions of changing this code yet: https://github.com/KingdomFirst/rock-attended-checkin/blob/master/cc_newspring/AttendedCheckin/Confirm.ascx.cs#L178-L183 

We will assign when we can get to it. If you would like to prioritize this fix, please contact sales@kingdomfirstsolutions.com.
